binutils: Disable gprofng on musl systems
disable gprofng, as it depends on few glibc apis

| ../../../gprofng/libcollector/../src/collector_module.h:78:13: error: duplicate member 'pwrite'
|    78 |   ssize_t (*pwrite64)();
|       |             ^~~~~~~~
| ../../../gprofng/libcollector/dispatcher.c: In function 'collector_timer_create':
| ../../../gprofng/libcollector/dispatcher.c:578:8: error: 'struct sigevent' has no member named '_sigev_un'
|   578 |   sigev._sigev_un._tid = __collector_gettid ();
|       |        ^

Signed-off-by: Khem Raj <raj.khem@gmail.com>